# -*- coding: utf-8 -*-
"""Copia di Copia di Modello.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YO2tFsySibWHYnIM-BzhX5KBmmSL6ITX
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
import os
import cv2
import shutil
import yaml
from pathlib import Path
from tqdm import tqdm
from collections import defaultdict, Counter

drive.mount('/content/drive')

!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
!pip install -r requirements.txt pyyaml tqdm

# CONFIGURAZIONE PERCORSI
original_base = "/content/drive/MyDrive/Dataset/dataset.v3i.yolov5pytorch"
resized_base = "/content/dataset_resized"
target_size = 640

# Creazione cartelle di destinazione locale 
splits = ["train", "valid", "test"]
for split in splits:
    os.makedirs(os.path.join(resized_base, split, "images"), exist_ok=True)
    os.makedirs(os.path.join(resized_base, split, "labels"), exist_ok=True)

# Loop di ridimensionamento
for split in splits:
    image_dir = os.path.join(original_base, split, "images")
    label_dir = os.path.join(original_base, split, "labels")

    image_files = list(Path(image_dir).glob("*.[jp][pn]g"))

    for img_path in tqdm(image_files, desc=f"Resizing {split}"):
        filename = img_path.name
        label_file = img_path.stem + ".txt"

        # Resize immagine
        img = cv2.imread(str(img_path))
        if img is None: continue
        resized_img = cv2.resize(img, (target_size, target_size))
        cv2.imwrite(os.path.join(resized_base, split, "images", filename), resized_img)

        # Copia label
        orig_label_path = os.path.join(label_dir, label_file)
        if os.path.exists(orig_label_path):
            shutil.copy(orig_label_path, os.path.join(resized_base, split, "labels", label_file))

print("\n✅ Resize completato e dataset spostato in locale (/content/dataset_resized)")

# Conteggio istanze per classe
label_dir = os.path.join(resized_base, "train/labels")
class_counts = Counter()

for f in os.listdir(label_dir):
    if f.endswith(".txt"):
        with open(os.path.join(label_dir, f)) as file:
            for line in file:
                class_id = int(line.split()[0])
                class_counts[class_id] += 1

print("Statistiche classi trovate:")
class_names = ["Pothole", "Circular Cover", "Rectangular Cover", "Speed Bump"]
for i, name in enumerate(class_names):
    print(f"Classe {i} ({name}): {class_counts[i]} istanze")

# Creazione file data.yaml
data_yaml_path = "/content/yolov5/road_data.yaml"
data_config = {
    'train': os.path.join(resized_base, 'train/images'),
    'val': os.path.join(resized_base, 'valid/images'),
    'nc': 4,
    'names': class_names
}

with open(data_yaml_path, 'w') as f:
    yaml.dump(data_config, f)

# Training con YOLOv5n 
!python train.py --img 640 --batch 16 --epochs 50 \
    --data {data_yaml_path} \
    --weights yolov5n.pt \
    --name road_fault_detection

import shutil
import os

source = "/content/yolov5/runs/train/road_fault_detection/weights/best.pt"
destination = "/content/drive/MyDrive/best_road_model.pt"

if os.path.exists(source):
    shutil.copy(source, destination)
    print("✅ Modello salvato sul tuo Google Drive come 'best_road_model.pt'!")
else:
    print("❌ Errore: percorso non trovato. Controlla il nome della cartella in yolov5/runs/train/")


!python export.py --weights /content/yolov5/runs/train/road_fault_detection/weights/best.pt --include onnx --img 640

from google.colab import files

files.download("/content/yolov5/runs/train/road_fault_detection/weights/best.pt")
files.download("/content/yolov5/runs/train/road_fault_detection/weights/best.onnx")